### ISSUE TITLE
请教一下，下图报错是什么原因

### ISSUE THREAD

**Issue by AnterWang** [devilwjp/uni-project-to-plugin#6]
<img width="1026" alt="图片" src="https://user-images.githubusercontent.com/23149546/101616383-44ba8f00-3a4a-11eb-84cc-a15e1a9e4d33.png">

**Comment by devilwjp** [comment]
首先确认一下预览的目录是什么？应该是dist/dev/mp-weixin-pack-plugin（或者dist/build/mp-weixin-pack-plugin）  
其次可以在小程序ide中手动打开app.json文件和project.config.json文件，看下内容是否正确

**Comment by AnterWang** [comment]
> 首先确认一下预览的目录是什么？应该是dist/dev/mp-weixin-pack-plugin（或者dist/build/mp-weixin-pack-plugin）
> 其次可以在小程序ide中手动打开app.json文件和project.config.json文件，看下内容是否正确

已解决，小程序开发者工具的问题，工具内看到内容都是正确的，但刷新或重新编译均无效，需小程序开发者工具重启
